#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          3
bspc config focused_border_color "#00e6e6"
bspc config focused_locked_border_color "7300e6"
bspc config normal_border_color "#7300e6"
bspc config click_to_focus true
bspc config top_padding 14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Atom desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Termite floating=on

xsetroot -cursor_name left_ptr

panel &
